prev_freq_map = {
# int numberOfGuestRooms; 
    'hotelContent.rooms.hotelHighlights.buildingDetails.numberOfGuestRooms': 'hotelinfo.facilities.rooms.hotelHighlights.buildingDetails.numberOfGuestRooms',
# int numberOfFloors;
    'hotelContent.rooms.hotelHighlights.buildingDetails.numberOfFloors': 'hotelinfo.facilities.rooms.hotelHighlights.buildingDetails.numberOfFloors',
# int numberOfSuites;
    'hotelContent.rooms.hotelHighlights.buildingDetails.numberOfSuites': 'hotelinfo.facilities.rooms.hotelHighlights.buildingDetails.numberOfSuites',
# int numberOfNonSmokingRooms;
    'hotelContent.rooms.hotelHighlights.buildingDetails.numberOfNonSmokingRooms': 'hotelinfo.facilities.rooms.hotelHighlights.buildingDetails.numberOfNonSmokingRooms',
# Parking parking;
    'hotelContent.facilities.parking.carParkingAvailable': 'hotelinfo.facilities.parking.carParkingAvailable',
    'hotelContent.facilities.parking.valetParkingAvailable': 'hotelinfo.facilities.valetParkingAvailable',
    'hotelContent.facilities.parking.dailyValetParkingFee': 'hotelinfo.facilities.parking.dailyValetParkingFee',
    'hotelContent.facilities.parking.parkingDescription': 'hotelinfo.facilities.parking.parkingDescription',
    'hotelContent.facilities.parking.numberOfParkingSpaces': 'hotelinfo.facilities.parking.numberOfParkingSpaces',
    'hotelContent.facilities.parking.chargeForParking': 'hotelinfo.facilities.chargeForParking',
    'hotelContent.facilities.parking.dailySelfParkingFee': 'hotelinfo.facilities.parking.dailySelfParkingFee',
    'hotelContent.facilities.parking.complimentaryDailySelfParking': 'hotelinfo.facilities.parking.complimentaryDailySelfParking',
# List<Attraction> attractions;
    'hotelContent.attractionsAndRecreation.corporateLocation.corporationDetails.corporationDetail': 'hotelinfo.facilities.attractionsandrecreation.corporateLocation.corporationDetails.corporationDetail',
    'hotelContent.attractionsAndRecreation.attractions.sightseeingTours': 'hotelinfo.facilities.attractionsandrecreation.attractions.sightseeingTours',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.parkDetails.parkDetail': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.parkDetails.parkDetail',
    'hotelContent.attractionsAndRecreation.attractions.museumOrGallery': 'hotelinfo.facilities.attractionsandrecreation.attractions.museumOrGallery',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.movieTheaterDetails.movieTheaterDetail': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.movieTheaterDetails.movieTheaterDetail',
    'hotelContent.attractionsAndRecreation.attractions.raceTrackDetails.raceTrackDetail': 'hotelinfo.facilities.attractionsandrecreation.attractions.raceTrackDetails.raceTrackDetail',
    'hotelContent.attractionsAndRecreation.attractions.zooOrAquariumDetails.zooOrAquariumDetail': 'hotelinfo.facilities.attractionsandrecreation.attractions.zooOrAquariumDetails.zooOrAquariumDetail',
    'hotelContent.attractionsAndRecreation.attractions.sportsVenueDetails.sportsVenueDetail': 'hotelinfo.facilities.attractionsandrecreation.attractions.sportsVenueDetails.sportsVenueDetail',
    'hotelContent.attractionsAndRecreation.attractions.themeParkDetails.themeParkDetail': 'hotelinfo.facilities.attractionsandrecreation.attractions.themeParkDetails.themeParkDetail',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.basketball': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.basketball',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.bicycling': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.bicycling',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.joggingTrack': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.joggingTrack',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.baseball': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.baseball',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.archery': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.archery',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.badminton': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.badminton',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.mountainOrRockWallClimbing': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.mountainOrRockWallClimbing',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.hunting': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.hunting',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.volleyball': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.volleyball',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.outdoorIceSkating': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.outdoorIceSkating',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.outdoorRollerSkating': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.outdoorRollerSkating',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.snowSkiing': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.snowSkiing',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.miniatureGolf': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.miniatureGolf',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.soccer': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.soccer',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.americanFootball': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.americanFootball',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.hiking': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.hiking',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.cricket': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.cricket',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.squash': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.squash',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.horsebackRiding': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.horsebackRiding',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.racquetBall': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.racquetBall',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.outdoorTennisCourts': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.outdoorTennisCourts',
    'hotelContent.attractionsAndRecreation.indoorRecreation.activitiesDescription': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.activitiesDescription',
    'hotelContent.attractionsAndRecreation.indoorRecreation.billiards': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.billiards',
    'hotelContent.attractionsAndRecreation.indoorRecreation.bowling': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.bowling',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorIceSkating': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.indoorIceSkating',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorRollerSkating': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.indoorRollerSkating',
    'hotelContent.attractionsAndRecreation.indoorRecreation.racquetBall': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.racquetBall',
    'hotelContent.attractionsAndRecreation.indoorRecreation.tableTennis': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.tableTennis',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorTennisCourts': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.indoorTennisCourts',
    'hotelContent.attractionsAndRecreation.indoorRecreation.tanningBeds': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.tanningBeds',
    'hotelContent.attractionsAndRecreation.waterRecreation.fishing': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.fishing',
    'hotelContent.attractionsAndRecreation.waterRecreation.jetSkiing': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.jetSkiing',
    'hotelContent.attractionsAndRecreation.waterRecreation.boatingOrSailing': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.boatingOrSailing',
    'hotelContent.attractionsAndRecreation.waterRecreation.scubaDiving': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.scubaDiving',
    'hotelContent.attractionsAndRecreation.waterRecreation.waterSkiing': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.waterSkiing',
    'hotelContent.attractionsAndRecreation.waterRecreation.swimming': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.swimming',
    'hotelContent.attractionsAndRecreation.waterRecreation.snorkeling': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.snorkeling',
    'hotelContent.attractionsAndRecreation.waterRecreation.surfing': 'hotelinfo.facilities.attractionsandrecreation.waterRecreation.surfing',
    'hotelContent.attractionsAndRecreation.attractions.collegeOrUniversityDetails.collegeOrUniversityDetail': 'hotelinfo.facilities.attractionsandrecreation.attractions.collegeOrUniversityDetails.collegeOrUniversityDetail',
    'hotelContent.attractionsAndRecreation.otherAttractions.libraryDetails.libraryDetail': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.libraryDetails.libraryDetail',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.churchName': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.churchName',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.churchLocation.distance': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.churchLocation.distance',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.churchLocation.direction': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.churchLocation.direction',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.mosqueName': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.mosqueName',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.mosqueLocation.distance': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.mosqueLocation.distance',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.mosqueLocation.direction': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.mosqueLocation.direction',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.synogogueName': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.synogogueName',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.synogogueLocation.distance': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.synogogueLocation.distance',
    'hotelContent.attractionsAndRecreation.otherAttractions.worshipLocations.synogogueLocation.direction': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.worshipLocations.synogogueLocation.direction',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.golfCourseDetails.golfCourseDetail': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.golfCourseDetails.golfCourseDetail',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.outdoorTennisCourts.distance': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.outdoorTennisCourts.distance',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorTennisCourts.distance': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreation.indoorTennisCourts.distance',
    'hotelContent.attractionsAndRecreation.indoorRecreation.tableTennis.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreationTableTennisOnSiteInd',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorTennisCourts.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreationIndoorTennisCourtsOnSiteInd',
    'hotelContent.attractionsAndRecreation.indoorRecreation.billiards.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreatioBilliardsOnSiteInd',
    'hotelContent.attractionsAndRecreation.indoorRecreation.bowling.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreationBowlingOnSiteInd',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorIceSkating.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.IndoorIceSkatingOnSiteInd',
    'hotelContent.attractionsAndRecreation.indoorRecreation.indoorRollerSkating.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.indoorRollerSkating',
    'hotelContent.attractionsAndRecreation.indoorRecreation.racquetBall.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.indoorRecreationRacquetBall',
    'hotelContent.attractionsAndRecreation.outdoorRecreation.golfCourseDetails': 'hotelinfo.facilities.attractionsandrecreation.outdoorRecreation.golfCourseDetails',
    'hotelContent.attractionsAndRecreation.indoorRecreation.tanningBeds.onSiteInd': 'hotelinfo.facilities.attractionsandrecreation.tanningBedsOnSiteInd',
    'hotelContent.attractionsAndRecreation.otherAttractions.attractionDetails.attractionDetail': 'hotelinfo.facilities.attractionsandrecreation.otherAttractions.attractionDetails.attractionDetail',
# Map<String, ImageGroup> imageGroups;
    'hotelContent.media.welcomePhotos': 'hotelInfo.media.welcomePhotos',
    'hotelContent.media.roomPhotos': 'hotelInfo.media.roomPhotos',
    'hotelContent.media.amenityPhotos': 'hotelInfo.media.amenityPhotos',
    'hotelContent.media.diningPhotos': 'hotelinfo.media.diningImages',
    'hotelContent.media.groupsandMeetingsPhotos': 'hotelInfo.media.groupsandMeetingsPhotos',
    'hotelContent.media.roomVirtualTours': 'hotelInfo.media.roomVirtualTours',
    'hotelContent.media.primaryPhotos': 'hotelInfo.media.primaryPhotos',
    'hotelContent.media.primaryPhotos.primaryWelcomePhoto.image.formats.format': 'hotelInfo.media.welcomePhotos',
    'hotelContent.media.primaryPhotos.primaryRoomPhoto.image.formats.format': 'hotelInfo.media.primaryPhotos',
    'hotelContent.media.primaryPhotos.primaryAmenityPhoto.image.formats.format': 'hotelInfo.media.primaryPhotos',
    'hotelContent.media.primaryPhotos.primaryDiningPhoto.image.formats.format': 'hotelInfo.media.primaryPhotos',
    'hotelContent.media.primaryPhotos.primaryGroupsAndMeetingsPhoto.image.formats.format': 'hotelInfo.media.primaryPhotos',
    'hotelContent.media.roomPhotos.guestRoomPhoto': 'hotelinfo.media.roomPhotos.guestRoomPhoto',
    'hotelContent.media.roomPhotos.suitePhoto': 'hotelinfo.media.roomPhotos.suitePhoto',
    'hotelContent.media.videos.customVideo.file.url': 'hotelinfo.media.videos.customVideo.file.url',
    'hotelContent.media.videos.customVideo.caption': 'hotelinfo.media.videos.customVideo.caption',
    'hotelContent.media.diningPhotos.barandLoungePhoto': 'hotelinfo.media.diningPhotos.barandLoungePhoto',
    'hotelContent.media.diningPhotos.restaurantPhoto': 'hotelinfo.media.diningPhotos.restaurantPhoto',
    'hotelContent.media.diningPhotos.fineDiningPhoto': 'hotelinfo.media.diningPhotos.fineDiningPhoto',
    'hotelContent.media.conciergeVideo.mainVideo.file.url': 'hotelinfo.media.conciergeVideo.mainVideo.file.url',
    'hotelContent.media.roomPhotos.kingBedGuestRoomPhoto': 'hotelinfo.media.roomPhotos.kingBedGuestRoomPhoto',
    'hotelContent.media.roomPhotos.clubFloorRoomPhoto': 'hotelinfo.media.roomPhotos.clubFloorRoomPhoto',
    'hotelContent.media.groupsandMeetingsPhotos.meetingRoomPhoto': 'hotelinfo.media.groupsandMeetingsPhotos.meetingRoomPhoto',
    'hotelContent.media.groupsandMeetingsPhotos.ballroomPhoto': 'hotelinfo.media.groupsandMeetingsPhotos.ballroomPhoto',
    'hotelContent.media.amenityPhotos.fitnessCenterPhoto': 'hotelinfo.media.amenityPhotos.fitnessCenterPhoto',
    'hotelContent.media.welcomePhotos.hotelExteriorPhoto': 'hotelinfo.media.welcomePhotos.hotelExteriorPhoto',
    'hotelContent.media.icDestinationPhotos.exterior.image.formats.format': 'hotelinfo.media.icDestinationPhotos.exterior.image.formats.format',
    'hotelContent.media.icDestinationPhotos.exterior.caption': 'hotelinfo.media.icDestinationPhotos.exterior.caption',
    'hotelContent.media.icDestinationPhotos.destinationInterior.image.formats.format': 'hotelinfo.media.icDestinationPhotos.destinationInterior.image.formats.format',
    'hotelContent.media.icDestinationPhotos.destinationInterior.caption': 'hotelinfo.media.icDestinationPhotos.destinationInterior.caption',
    'hotelContent.media.icDestinationPhotos.interior.image.formats.format': 'hotelinfo.media.icDestinationPhotos.interior.image.formats.format',
    'hotelContent.media.icDestinationPhotos.interior.caption': 'hotelinfo.media.icDestinationPhotos.interior.caption',
    'hotelContent.media.icDestinationPhotos.insiderKnowledge.image.formats.format': 'hotelinfo.media.icDestinationPhotos.insiderKnowledge.image.formats.format',
    'hotelContent.media.icDestinationPhotos.insiderKnowledge.caption': 'hotelinfo.media.icDestinationPhotos.insiderKnowledge.caption',
    'hotelContent.media.icDestinationPhotos.atYourSide.image.formats.format': 'hotelinfo.media.icDestinationPhotos.atYourSide.image.formats.format',
    'hotelContent.media.icDestinationPhotos.atYourSide.caption': 'hotelinfo.media.icDestinationPhotos.atYourSide.caption',
    'hotelContent.media.icDestinationPhotos.welcome1.image.formats.format': 'hotelinfo.media.icDestinationPhotos.welcome1.image.formats.format',
    'hotelContent.media.icDestinationPhotos.welcome1.caption': 'hotelinfo.media.icDestinationPhotos.welcome1.caption',
    'hotelContent.media.icDestinationPhotos.welcome2.image.formats.format': 'hotelinfo.media.icDestinationPhotos.welcome2.image.formats.format',
    'hotelContent.media.icDestinationPhotos.welcome2.caption': 'hotelinfo.media.icDestinationPhotos.welcome2.caption',
    'hotelContent.media.requests': 'hotelinfo.media.requests',
    'hotelContent.media.icDestinationPhotos.welcomeImages': 'hotelinfo.media.icDestinationPhotos.welcomeImages',
    'hotelContent.media.icDestinationPhotos.welcomeVirtualImages': 'hotelinfo.media.icDestinationPhotos.welcomeVirtualImages',
    'hotelContent.media.roomPhotos.guestRoomsImages': 'hotelinfo.media.roomPhotos.guestRoomsImages',
    'hotelContent.media.roomPhotos.guestRoomsVirtualImages': 'hotelinfo.media.roomPhotos.guestRoomsVirtualImages',
    'hotelContent.media.diningVirtualImages': 'hotelinfo.media.diningVirtualImages',
    'hotelContent.media.groupsandMeetingsPhotos.meetingImages': 'hotelinfo.media.groupsandMeetingsPhotos.meetingImages',
    'hotelContent.media.groupsandMeetingsPhotos.meetingVirtualImages': 'hotelinfo.media.groupsandMeetingsPhotos.meetingVirtualImages',
    'hotelContent.media.amenityVirtualImages': 'hotelinfo.media.amenityVirtualImages',
    'hotelContent.media.areaAttractionPhoto': 'hotelinfo.media.areaAttractionPhoto',
# AccessibilityDetails accessibilityDetails;

'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.disabledParking': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.disabledParking',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.adaAccessibleSelfParkingAvailable': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.adaAccessibleSelfParkingAvailable',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.vanAccessibleParkingInSelfParking': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.vanAccessibleParkingInSelfParking',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.complimentaryAccessibleTransportationWithAdvancedNotice': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.complimentaryAccessibleTransportationWithAdvancedNotice',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.noOfWheelchairParkingSpace': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.noOfWheelchairParkingSpace',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.designatedAccessibleParkingSpacesWithPostSigns': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.designatedAccessibleParkingSpacesWithPostSigns',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.flatTerrainBetweenParkingAndEntrance': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.flatTerrainBetweenParkingAndEntrance',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.rampAccessDetails.toProperty': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.rampAccessDetails.toProperty',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.rampAccessDetails.toHotelbarLounge': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.rampAccessDetails.toHotelbarLounge',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.rampAccessDetails.toHotelRestaurant': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.rampAccessDetails.toHotelRestaurant',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.parkingDropOffPointAdjToEntrance': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.parkingDropOffPointAdjToEntrance',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.hotelEntranceisADAAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.hotelEntranceisADAAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.entrancesOrDoorsAreADAAccessibleWithBeveledOrFlushThresholds': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.entrancesOrDoorsAreADAAccessibleWithBeveledOrFlushThresholds',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToRegistrationAreaAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToRegistrationAreaAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.publicRestroomsStallsAreWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.publicRestroomsStallsAreWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.conciergeDeskADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.conciergeDeskADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.hotelRestaurantADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.hotelRestaurantADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.exerciseFacilityADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.exerciseFacilityADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.businessCenterADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.businessCenterADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.registrationDeskADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.registrationDeskADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.publicRestroomsAreWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.publicRestroomsAreWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.hotelEntranceIsWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.hotelEntranceIsWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.wheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.wheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.wheelchairAccessibleRooms': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.wheelchairAccessibleRooms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.poolADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.poolADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpairedHospitalityKitsIncludingVisualAlarms': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpairedHospitalityKitsIncludingVisualAlarms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToBusinessCenterAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToBusinessCenterAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routeFromAccessibleEntranceToMeetingBallRoomAreaIsAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routeFromAccessibleEntranceToMeetingBallRoomAreaIsAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToExerciseFacilityAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToExerciseFacilityAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToPoolAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToPoolAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.accessToAllLevels': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.accessToAllLevels',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.adaCompliant': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.adaCompliant',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.elevatorNearAccessibleRooms': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.elevatorNearAccessibleRooms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.guestRoomsAndAccessRoutesAreADAAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.guestRoomsAndAccessRoutesAreADAAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.allDoorLocksAndHardwareAreADAAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.allDoorLocksAndHardwareAreADAAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.controlsforHeatingAirConditionerLightsAreWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.controlsforHeatingAirConditionerLightsAreWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.furnitureRearrangeable': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.furnitureRearrangeable',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.emergencyCordOrButtonInBathrooms': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.emergencyCordOrButtonInBathrooms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.emergencyCordOrButtonInBedrooms': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.emergencyCordOrButtonInBedrooms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.grabBarsWithSpaceAndTailToilets': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.grabBarsWithSpaceAndTailToilets',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.bathroomWithClearTurningSpace': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.bathroomWithClearTurningSpace',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.tubWithGrabBarsOnTwoAdjacentWalls': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.tubWithGrabBarsOnTwoAdjacentWalls',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.portableBathtubSeats': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.portableBathtubSeats',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.bathTubSeat': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.bathTubSeat',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.showersWithHandHeldShowerOrHose': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.showersWithHandHeldShowerOrHose',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.showersWithBuiltInTransferShowerSeats': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.showersWithBuiltInTransferShowerSeats',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.handrails': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.handrails',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.rollInShowers': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.rollInShowers',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.raisedToiletWithGrabBars': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.raisedToiletWithGrabBars',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.safetyBar': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.safetyBar',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.bathroomDoorsOpenOutwardInAccessibleRooms': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.bathroomDoorsOpenOutwardInAccessibleRooms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.accessibleBathroomControls': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.accessibleBathroomControls',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.brailleInGuestRooms': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.brailleInGuestRooms',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleSmokeFireAlarm.inGuesRoom': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleSmokeFireAlarm.inGuesRoom',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleSmokeFireAlarm.inHallways': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleSmokeFireAlarm.inHallways',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleSmokeFireAlarm.inPublicAreas': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleSmokeFireAlarm.inPublicAreas',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.emergencyInstructionInFourteenPtPrint': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.emergencyInstructionInFourteenPtPrint',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.emergencyInstructionInBraille': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.emergencyInstructionInBraille',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.brailleOnElevatorsAndPublicAreas': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.brailleOnElevatorsAndPublicAreas',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.vibratingPillowsAvailable': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.vibratingPillowsAvailable',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.onSiteRestMenusInBraille': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.onSiteRestMenusInBraille',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.fourteenPntPrintMenusInOnsiteRest': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.fourteenPntPrintMenusInOnsiteRest',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleAlarmsInHallways': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.audibleAlarmsInHallways',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualAlarmOrAlert.inGuestRooms': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualAlarmOrAlert.inGuestRooms',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualAlarmOrAlert.inHallways': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualAlarmOrAlert.inHallways',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualAlarmOrAlert.inPublicAreas': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualAlarmOrAlert.inPublicAreas',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.closeCaptionTV': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.closeCaptionTV',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.telephonesWithAmplifierOrTDD': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.telephonesWithAmplifierOrTDD',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.knockLights': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.knockLights',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.televisionAmplifier': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.televisionAmplifier',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.hearingImpairedServicesOffered': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.hearingImpairedServicesOffered',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.staffProficientInSignLanguage': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.hearingImpariedServiceDetails.staffProficientInSignLanguage',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.wheelChairAccessibilityDetails': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.wheelChairAccessibilityDetails',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.wheelchairAvailable': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.wheelchairAvailable',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.curbCutsAndStreetParkingWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.curbCutsAndStreetParkingWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails',
    'hotelContent.safetyAndAccessibility.fireSafety.windowsOpenByGuest.executiveRooms': 'hotelinfo.safetyAndAccessibility.fireSafety.windowsOpenByGuest.executiveRooms',
    'hotelContent.safetyAndAccessibility.fireSafety.windowsOpenByGuest.suites': 'hotelinfo.safetyAndAccessibility.fireSafety.windowsOpenByGuest.suites',
    'hotelContent.safetyAndAccessibility.fireSafety.windowsOpenByGuest.standardRooms': 'hotelinfo.safetyAndAccessibility.fireSafety.windowsOpenByGuest.standardRooms',
    'hotelContent.rooms.safetyAndAccessibility.fireSafety.windowsOpenByGuest': 'hotelinfo.rooms.safetyAndAccessibility.fireSafety.windowsOpenByGuest',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.closetsWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.closetsWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.guestRoomsAndAccessRoutesAreWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.guestRoomsAndAccessRoutesAreWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.guestRoomPlumbingIsPaddedWithClearanceBeneathVanity': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.guestRoomPlumbingIsPaddedWithClearanceBeneathVanity',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.adaAccessibleRooms': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.guestroomAccessibilityDetails.adaAccessibleRooms',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToRestaurantAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToRestaurantAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.publicRestroomsPlumbingIsPaddedWithClearanceBeneathVanity': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.publicRestroomsPlumbingIsPaddedWithClearanceBeneathVanity',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.onsiteRestaurantsHaveSeatingAvailableForWheelchairs': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.onsiteRestaurantsHaveSeatingAvailableForWheelchairs',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.accessibleFacilitiesInPublicAreas': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.accessibleFacilitiesInPublicAreas',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToSpaAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.routefromAccessiblePublicEntranceToSpaAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.businessCenterADAWheelchairAccessible': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.parkingAccessibilityDetails.businessCenterADAWheelchairAccessible',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.elevatorNearAccessibleRoom': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.elevatorAccessibilityDetails.elevatorNearAccessibleRoom',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.entrancesOrDoorsAreADAAccessibleWithBeveledOrFlushThresholds': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.publicAreaAccessibilityDetails.entrancesOrDoorsAreADAAccessibleWithBeveledOrFlushThresholds',
    'hotelContent.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.raisedToiletWithGrabBar': 'hotelinfo.safetyAndAccessibility.wheelChairAccessibility.bathroomAccessibilityDetails.raisedToiletWithGrabBar',
    'hotelContent.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.brailleOnElevatorsAndPublicArea': 'hotelinfo.safetyAndAccessibility.visuallyAndHearingImpairedService.visualImpariedServiceDetails.brailleOnElevatorsAndPublicArea',
# List<String> creditCards;
    'hotelContent.generalPropertyDetails.paymentMethods.creditCardsAccepted.listItem': 'hotelInfo.fees.paymentMethods.creditCardsAccepted',
# final List<HotelInternet> internet
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.complimentaryStandardWirelessForAllMembers': 'hotelinfo.facilities.wirelessInternet',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.standardRoomAvailable': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.standardRoomAvailable',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.executiveRoomAvailable': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.executiveRoomAvailable',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.suiteAvailable': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.suiteAvailable',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.businessCenterAvailable': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.businessCenterAvailable',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.meetingSpaceAvailable': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.meetingSpaceAvailable',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.publicSpaceAvailable': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.publicSpaceAvailable',
    'hotelContent.guestServices.internetServices.wiredHighSpeedInternetAccessDetails.premiumWiredInternetAvailable': 'hotelInfo.badges.premiumWiredInternetAvailable',
    'hotelContent.guestServices.internetServices.wiredHighSpeedInternetAccessDetails.complimentaryPremiumWiredInternetForEliteMembers': 'hotelInfo.badges.complimentaryPremiumWiredInternetForEliteMembers',
    'hotelContent.guestServices.internetServices.wiredHighSpeedInternetAccessDetails.complimentaryPremiumWiredInternetForAllMembers': 'hotelinfo.badges.complimentaryPremiumWiredInternetForAllMembers',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.standardRoomAvailable': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.standardRoomAvailable',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.executiveRoomAvailable': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.executiveRoomAvailable',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.suiteAvailable': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.suiteAvailable',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.businessCenterAvailable': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.businessCenterAvailable',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.meetingSpaceAvailable': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.meetingSpaceAvailable',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.publicSpaceAvailable': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.publicSpaceAvailable',
    'hotelContent.guestServices.internetServices.wiredHighSpeedInternetAccessDetails.complimentaryStandardWiredInternetForEliteMembers': 'hotelInfo.badges.complimentaryStandardWiredInternetForEliteMembers',
    'hotelContent.guestServices.internetServices.wiredHighSpeedInternetAccessDetails.complimentaryStandardWiredInternetForAllMembers': 'hotelInfo.badges.complimentaryStandardWiredInternetForAllMembers',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.complimentaryStandardWirelessForEliteMembers': 'hotelInfo.badges.complimentaryStandardWirelessForEliteMembers',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.premiumWirelessInternetAvailable': 'hotelInfo.badges.premiumWirelessInternetAvailable',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.complimentaryPremiumWirelessInternetForEliteMembers': 'hotelInfo.badges.complimentaryPremiumWirelessInternetForEliteMembers',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.complimentaryPremiumWirelessInternetForAllMembers': 'hotelInfo.badges.complimentaryPremiumWirelessInternetForAllMembers',
    'hotelContent.guestServices.internetServices.wiredHighSpeedInternetAccessDetails': 'hotelinfo.facilities.guestservices.internetServices.wiredHighSpeedInternetAccessDetails',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails': 'hotelinfo.facilities.guestservices.internetServices.wirelessHighSpeedInternetAccessDetails',
    'hotelContent.guestServices.internetServices.premiumInternetFee': 'hotelinfo.facilities.guestservices.internetServices.premiumInternetFee',
    'hotelContent.guestServices.internetServices.highSpeedInternetLocations.standardRoomFee': 'hotelinfo.facilities.guestservices.internetServices.highSpeedInternetLocations.standardRoomFee',
    'hotelContent.guestServices.internetServices.wirelessInternetLocations.standardRoomFee': 'hotelinfo.facilities.guestservices.internetServices.wirelessInternetLocations.standardRoomFee',
    'hotelContent.facilities.businessCenter.businessCenterPCDetails.emailAndInternet': 'hotelInfo.facilities.emailAndInternet',
    'hotelContent.guestServices.internetServices.internetBrowserOnTVLocations': 'hotelinfo.facilities.guestservices.internetServices.internetBrowserOnTVLocations',
    'hotelContent.guestServices.internetServices.internetBrowserOnTVLocations.standardRoomAvailable': 'hotelinfo.facilities.guestservices.internetServices.internetBrowserOnTVLocations.standardRoomAvailable',
    'hotelContent.guestServices.internetServices.internetBrowserOnTVLocations.suiteAvailable': 'hotelinfo.facilities.guestservices.internetServices.internetBrowserOnTVLocations.suiteAvailable',
    'hotelContent.guestServices.internetServices.highSpeedInternetAccess': 'hotelinfo.facilities.GuesthighSpeedInternetAccess',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.premiumWirelessInternetAvailable': 'hotelInfo.badges.premiumWirelessInternetAvailable',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.complimentaryPremiumWirelessInternetForEliteMembers': 'hotelInfo.badges.complimentaryPremiumWirelessInternetForEliteMembers',
    'hotelContent.guestServices.internetServices.wirelessHighSpeedInternetAccessDetails.complimentaryPremiumWirelessInternetForAllMembers': 'hotelInfo.badges.complimentaryPremiumWirelessInternetForAllMembers',
# final Map<String, HotelInternet> hotelInternetMap List<Feature> petPolicy;
    'hotelContent.generalPropertyDetails.petPolicy.petsAllowed': 'hotelInfo.policies.pets.petsAllowed',
    'hotelContent.generalPropertyDetails.petPolicy.guideDogsOrServiceAnimalsAllowed': 'hotelInfo.policies.pets.guideDogsOrServiceAnimalsAllowed',
    'hotelContent.generalPropertyDetails.petPolicy.petDepositPerStay': 'hotelinfo.policies.pets.DepositPerStay',
    'hotelContent.generalPropertyDetails.petPolicy.petFeePerNight': 'hotelinfo.policies.pets.FeePerNight',
    'hotelContent.generalPropertyDetails.petPolicy.description': 'hotelinfo.policies.pets.description',
    'hotelContent.generalPropertyDetails.petPolicy.petWalkingArea': 'hotelinfo.policies.pets.petWalkingArea',
# HotelEstablishmentDetails establishmentDetails final List<String> languages
        'hotelContent.guestServices.staffAssistedServices.languageDetails.languages.listItem': 'hotelinfo.facilities.guestservices.staffAssistedServices.languageDetails.languages',
    'hotelContent.guestServices.staffAssistedServices.languageDetails.multipleLanguages': 'hotelinfo.facilities.languageDetailsMultipleLanguages',
    'hotelContent.guestServices.staffAssistedServices.languageDetails.languages.listItem+B76:B87': 'hotelinfo.profile.languagesSpokenByStaff',
# ======
 # Field #7030 Hotel Stay Preference Participation
    'hotelContent.generalPropertyDetails.profile.stay_preference_participation': 'hotelInfo.profile.stayPreferenceParticipation',
# -Field #40 Digital Room Service
    'hotelContent.unknown.DigitalRoomService': 'hotelInfo.technology.digitalRoomService',
# -Field #113 Open Table Market
    'hotelContent.unknown.restaurant.op.openTableApiKey': 'hotelInfo.facilities.restaurant.openTableApiKey',
# -Field #114 Grubhub Market
    'hotelContent.unknown.GrubhubMarket': 'hotelInfo.technology.grubhubMarket',
# -Field #1417 Number of On-Site Restaurants
'hotelContent.facilities.restaurant.onSiteRestaurantsCount': 'hotelinfo.facilities.restaurant.onSiteRestaurantsCount',
# - Field #288 Hours of Operation
'hotelContent.unknown.restaurant.op.hoursFrom': 'hotelInfo.facilities.restaurant.operation.hoursFrom',
    'hotelContent.unknown.restaurant.op.hoursTo': 'hotelInfo.facilities.restaurant.operation.hoursTo',
# - Field #6030 Room Service Menu PDF
# - Field #6027 Restaurant Menu PDF
# - Field #6028 Bar and Lounge PDF
    'hotelContent.unknown.RoomServiceMenuPDF': 'hotelInfo.facilities.restaurant.roomServiceMenuPDF',
    'hotelContent.unknown.restaurant.op.RestaurantMenuPDF': 'hotelInfo.facilities.restaurant.restaurantMenuPDF',
    'hotelContent.unknown.barandlounge.pdf': 'hotelInfo.facilities.barAndLounge.menuPDF',
# - Field #258 Hours of Operation
    'hotelContent.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursFrom': 'hotelinfo.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursFrom',
    'hotelContent.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursTo': 'hotelinfo.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursTo',
    'hotelContent.facilities.restaurant.restaurantDetails.restaurantDetail': 'hotelinfo.facilities.restaurant.restaurantDetails.restaurantDetail',
    'hotelContent.facilities.restaurant.roomServiceDetails.fullOrLimitedMenu': 'hotelinfo.facilities.restaurant.roomServiceDetails.fullOrLimitedMenu',
    'hotelContent.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursFrom': 'hotelinfo.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursFrom',
    'hotelContent.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursTo': 'hotelinfo.facilities.restaurant.roomServiceDetails.hoursOfOperation.hoursTo',
    'hotelContent.facilities.restaurant.roomServiceDetails.menu.url': 'hotelinfo.facilities.restaurant.roomServiceDetails.menu.url',
    'hotelContent.facilities.restaurant.onSiteRestaurantsCount': 'hotelinfo.facilities.restaurant.onSiteRestaurantsCount',
    'hotelContent.facilities.restaurant.roomServiceDetails.roomService': 'hotelinfo.facilities.restaurant.roomServiceDetails.roomService',
    'hotelContent.facilities.restaurant.roomServiceDetails.roomService.executiveRooms': 'hotelinfo.facilities.restaurant.roomServiceDetails.roomService.executiveRooms',
    'hotelContent.facilities.restaurant.roomServiceDetails.roomService.suites': 'hotelinfo.facilities.restaurant.roomServiceDetails.roomService.suites',
    'hotelContent.facilities.restaurant.roomServiceDetails.roomService.standardRooms': 'hotelinfo.facilities.restaurant.roomServiceDetails.roomService.standardRooms',
    'hotelContent.facilities.restaurant.restaurantDetails.restaurantDetail.name': 'hotelinfo.facilities.restaurant.restaurantDetails.restaurantDetail.name',
    'hotelContent.unknown.RoomServiceMenuPDF': 'hotelInfo.facilities.restaurant.roomServiceMenuPDF',
    'hotelContent.unknown.restaurantnAme': 'hotelInfo.facilities.restaurant.name',
    'hotelContent.unknown.restaurant.cuisineType': 'hotelInfo.facilities.restaurant.cuisineType',
    'hotelContent.unknown.restaurant.DaysOfWeekOpen': 'hotelInfo.facilities.restaurant.operation.daysOfWeekOpen',
    'hotelContent.unknown.restaurant.op.hoursFrom': 'hotelInfo.facilities.restaurant.operation.hoursFrom',
    'hotelContent.unknown.restaurant.op.hoursTo': 'hotelInfo.facilities.restaurant.operation.hoursTo',
    'hotelContent.unknown.restaurant.op.phoneNumber': 'hotelInfo.facilities.restaurant.phoneNumber',
    'hotelContent.unknown.restaurant.op.RestaurantMenuPDF': 'hotelInfo.facilities.restaurant.restaurantMenuPDF',
    'hotelContent.unknown.restaurant.op.openTableApiKey': 'hotelInfo.facilities.restaurant.openTableApiKey',
    'hotelContent.unknown.restaurant.address': 'hotelInfo.facilities.restaurant.address',
    'hotelContent.unknown.restaurant.location': 'hotelInfo.facilities.restaurant.location',
  # - Field #276 Restaurant Name
  # - Field #1687 Cuisine Type
  # - Field #1782 Days of Week Open
  # - Field #277 Hours of Operation
  # - Field #1781 Restaurant Phone Number
  # - Field #6027 Restaurant Menu PDF
  # - Field #6313 OpenTable API Key (if restaurant can be booked on OpenTable)
  # - Field #276 Restaurant Name
  # - Field #1687 Cuisine Type
  # - Field #277 Hours of Operation
  # - Field #1781 Restaurant Phone Number
  # - Field #6027 Restaurant Menu PDF
  # - Field #1780 Restaurant Address
  # - Field #1404 Restaurant Location (Distance)
  # - Field #264 Days of Week
  # - Field #265 Hours of Operation
  # - Field #300 Bar Lounge Name
    'hotelContent.facilities.barAndLounge.liveEntertainmentAvailable': 'hotelinfo.facilities.barandlounge.liveEntertainmentAvailable',
    'hotelContent.facilities.barAndLounge.barLoungeDetails.barLoungeDetail': 'hotelInfo.policies.barLoungeDetail',
    'hotelContent.facilities.barAndLounge.cocktailLounge': 'hotelinfo.facilities.barAndLoungeCocktailLounge',
    'hotelContent.facilities.barAndLounge.champagneBar': 'hotelinfo.facilities.barAndLoungeChampagneBar',
    'hotelContent.facilities.barAndLounge.lounge24Hrs': 'hotelinfo.facilities.barAndLoungeLounge24Hrs',
    'hotelContent.facilities.barAndLounge.wineTasting.onSiteInd': 'hotelinfo.facilities.wineTastingOnSiteInd',
    'hotelContent.facilities.barAndLounge.nightClub.onSiteInd': 'hotelinfo.facilities.nightClubOnSiteInd',
    'hotelContent.facilities.barAndLounge.dedicatedLounge': 'hotelinfo.facilities.barAndLoungeDedicatedLounge',
    'hotelContent.facilities.barAndLounge.lounge24Hr': 'hotelinfo.facilities.barAndLoungeLounge24Hrs',
    'hotelContent.unknown.barandloung.name': 'hotelInfo.facilities.barAndLounge.name',
    'hotelContent.unknown.barandloung.loc': 'hotelInfo.facilities.barAndLounge.location',
    'hotelContent.unknown.barandloung.op.hrsto': 'hotelInfo.facilities.barAndLounge.operation.hoursTo',
    'hotelContent.unknown.barandloung.op.hrsfrom': 'hotelInfo.facilities.barAndLounge.operation.hoursFrom',
    'hotelContent.unknown.barandloung.phoneNumber': 'hotelInfo.facilities.barAndLounge.phoneNumber',
    'hotelContent.unknown.barandloung.pdf': 'hotelInfo.facilities.barAndLounge.menuPDF',
    'hotelContent.unknown.roomservice': 'hotelInfo.facilities.barAndLounge.menuPDF',
#   - Field #301 Bar Lounge Hours of Operation
#   - Field #5604 Bar Lounge Phone Number
#   - Field #6028 Bar and Lounge PDF
# Field #286 Room Service is set to ALL or SOME
    'hotelContent.unknown.roomservice': 'hotelInfo.policies.roomservice',
# Fields #259, #260, or #261 Complimentary Breakfast
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet': 'hotelInfo.facilities.foodandbeverage.complimentaryBreakfastBuffet',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryCoffeeInLobby': 'hotelInfo.facilities.foodandbeverage.complimentaryCoffeeInLobby',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast.executiveRooms': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast.executiveRooms',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast.suites': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast.suites',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast.standardRooms': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryFullBreakfast.standardRooms',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast.executiveRooms': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast.executiveRooms',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast.suites': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast.suites',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast.standardRooms': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryContiBreakfast.standardRooms',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet.executiveRooms': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet.executiveRooms',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet.suites': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet.suites',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet.standardRooms': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryBreakfastBuffet.standardRooms',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryBreakfastHoursOfOperation.hoursTo': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryBreakfastHoursOfOperation.hoursTo',
    'hotelContent.facilities.foodAndBeverage.complimentaryBreakfastDetails.complimentaryBreakfastHoursOfOperation.hoursFrom': 'hotelinfo.facilities.foodandbeverage.complimentaryBreakfastDetails.complimentaryBreakfastHoursOfOperation.hoursFrom',
    'hotelContent.facilities.foodAndBeverage.eveningReceptionDetails.daysOpen': 'hotelInfo.facilities.foodAndBeverage.eveningReceptionDetails.daysOpen',
    'hotelContent.facilities.foodAndBeverage.eveningReceptionDetails.eveningReceptionInd': 'hotelInfo.facilities.foodAndBeverage.eveningReceptionDetails.eveningReceptionInd',
    'hotelContent.facilities.foodAndBeverage.eveningReceptionDetails.hourOfOperation.hoursTo': 'hotelInfo.facilities.foodAndBeverage.eveningReceptionDetails.hourOfOperation.hoursTo',
    'hotelContent.facilities.foodAndBeverage.eveningReceptionDetails.hourOfOperation.hoursFrom': 'hotelInfo.facilities.foodAndBeverage.eveningReceptionDetails.hourOfOperation.hoursFrom',
# - Field #296 Bar Lounge Details is completed AND
# - Field #5005 Bar Lounge Location is set to ON-SITE
# Field #233 Barbeque Grills is set to YES
'hotelContent.facilities.publicAreas.barbequeGrills': 'hotelinfo.facilities.publicareas.barbequegrills',
}



